apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  user: YWRtaW4=
  password: THhkZGY3cHFoZw==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  password: cEQzZ2ZFR0hWTQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  access-key: bXNhLWZyYW1ld29yaw==
  secret-key: bXNhLWZyYW1ld29yay1taW5pbw==
